spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<inserire nome database>
    username: root
    password: <inserire password>

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
